# This file was generated by `cabal2nix ./. > shell.nix`,
# then edited to work as a development environment
# and to include custom dependencies from github.
#
# Use `nix-shell --pure` to set everything up.
#
# Because it's "pure" (all dependencies are explicit),
# you need to add your text editor and any other tools
# to devDepends below.

# TODO depend on custom filestore, not the system one!
# TODO rewrite gitit.sh to use nix rather than custom build
# TODO is there an official attr for runDepends?
# TODO add pkill to runDepends

{ pkgs ? (import <nixpkgs> {}).pkgs }:

let
  inherit (pkgs) haskellPackages;
  runDepends = with pkgs; [
    R
    bash
    graphviz
    perl
    python
    # texLive # TODO install after expanding root partition
  ];
  devDepends = with pkgs; [
    haskellPackages.cabalInstall
    git
    less
    vim
  ];
  # myFilestore = fetchgit {
  #   # TODO write me
  #   # TODO need a default.nix in the repo?
  # };

in haskellPackages.cabal.mkDerivation (self: {
  pname = "gitit";
  version = "0.10.5.1";
  src = ./.;
  isLibrary = true;
  isExecutable = true;

  buildDepends = with haskellPackages; devDepends ++ runDepends ++ [
    aeson base64Bytestring blazeHtml ConfigFile feed filepath filestore # myFilestore
    ghcPaths happstackServer highlightingKate hoauth2 hslogger
    HStringTemplate HTTP httpClientTls httpConduit json mtl network
    networkUri pandoc pandocTypes parsec random recaptcha safe SHA
    split syb tagsoup text time uri url utf8String uuid xhtml xml
    xssSanitize zlib
  ];

  meta = {
    homepage = "http://gitit.net";
    description = "Wiki using happstack, git or darcs, and pandoc";
    license = "GPL";
    platforms = self.ghc.meta.platforms;
  };
})
